service: daw-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/hola
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  categorias:
    handler: src/modules/categorias/controllers.main
    timeout: 30
    events:
      - http:
          path: api/categorias
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/categorias
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/categorias/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/categorias/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/categorias/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  compras:
    handler: src/modules/compras/controllers.main
    timeout: 30
    events:
      - http:
          path: api/compras
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/compras
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/compras/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/compras/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/compras/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  favoritos:
    handler: src/modules/favoritos/controllers.main
    timeout: 30
    events:
      - http:
          path: api/favoritos
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/favoritos
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/favoritos/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/favoritos/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/favoritos/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  generos:
    handler: src/modules/generos/controllers.main
    timeout: 30
    events:
      - http:
          path: api/generos
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/generos
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/generos/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/generos/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/generos/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  productos:
    handler: src/modules/productos/controllers.main
    timeout: 30
    events:
      - http:
          path: api/productos
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/productos
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/productos/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/productos/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/productos/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  usuarios:
    handler: src/modules/usuarios/controllers.main
    timeout: 30
    events:
      - http:
          path: api/usuarios
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/usuarios
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/usuarios/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/usuarios/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
      - http:
          path: api/usuarios/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  chatbot:
    handler: src/services/chatbot/chatbot.main
    timeout: 30
    events:
      - http:
          path: api/chatbot
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  ayudaProducto:
    handler: src/services/chatbot/ayudaProductoController.main
    timeout: 30
    events:
      - http:
          path: api/chatbot/ayuda-producto
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  login:
    handler: src/modules/login/controllers.login
    timeout: 30
    events:
      - http:
          path: api/login
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  refreshToken:
    handler: src/modules/login/controllers.refreshToken
    timeout: 30
    events:
      - http:
          path: api/refresh-token
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
  register:
    handler: src/modules/register/controllers.register
    timeout: 30
    events:
      - http:
          path: api/register
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - Access-Control-Allow-Origin
            allowCredentials: true
